version: '3'

services:
  runshell:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: runshell:latest
    container_name: runshell
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../scripts:/app/scripts
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped 